### ISSUE TITLE
new bucket and subdomain for sparrow

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-marb-js#14]
tried to create a sparrow.wim.usgs.gov bucket in s3 but access is denied.  Can we get a new bucket from which to deploy sparrow apps?

--should be sparrow.wim.usgs.gov
--Route53 and any other settings the same as wim.usgs.gov bucket

**Comment by aaronstephenson** [comment]
Done.

https://sparrow.wim.usgs.gov
