### ISSUE TITLE
requesting Access to Mario to see if MXD files exist for Sparrow projects entitled TN, Great Lakes and MRB.

### ISSUE THREAD

**Issue by rstevensonUSGS** [USGS-WiM/sparrow-marb-js#53]
If i could have access to the Mario server in order to see if the MXD files for MRB, Tenn and Great lakes are there so I can re process the services to point at sparrow prod  rather than sparrow test that would be helpful.

**Comment by aaronstephenson** [comment]
I assume this is taken care of?

**Comment by rstevensonUSGS** [comment]
Yes, This is taken care of.
